use std::fs;
use std::io;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use crate::{
    Binding, BindingDocument, BindingDocumentError, BindingTarget, ElementId, HandlerId, UiEvent,
};

const GPUI_MCP_REPOSITORY: &str = "https://github.com/themixednuts/gpui-mcp";

/// Inputs for a new standalone GPUI HTML project.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ProjectOptions {
    name: String,
    destination: PathBuf,
    dependencies: ProjectDependencies,
    window_decorations: OutputWindowDecorations,
}

#[derive(Clone, Debug, Default, Eq, PartialEq)]
enum ProjectDependencies {
    #[default]
    PublicRepository,
    LocalWorkspace(PathBuf),
}

/// Cross-platform window decoration policy used by generated GPUI applications.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub enum OutputWindowDecorations {
    /// Ask Windows, macOS, and the Linux compositor/window manager for native decorations.
    #[default]
    Native,
    /// Hide the Windows/macOS system titlebar and request Linux client-side decorations.
    Custom,
}

impl OutputWindowDecorations {
    /// Generate the complete GPUI window-options module consumed by scaffolded applications.
    #[must_use]
    pub fn rust_module_source(self) -> String {
        let (transparent, linux) = match self {
            Self::Native => (false, "Server"),
            Self::Custom => (true, "Client"),
        };
        format!(
            r"// Generated by GPUI Studio / gpui-mcp-html. The document owns any custom titlebar.
use gpui::{{Bounds, Pixels, TitlebarOptions, WindowBounds, WindowDecorations, WindowOptions}};

pub fn output_window_options(bounds: Bounds<Pixels>) -> WindowOptions {{
    WindowOptions {{
        window_bounds: Some(WindowBounds::Windowed(bounds)),
        titlebar: Some(TitlebarOptions {{
            appears_transparent: {transparent},
            ..TitlebarOptions::default()
        }}),
        window_decorations: Some(WindowDecorations::{linux}),
        ..WindowOptions::default()
    }}
}}
"
        )
    }
}

impl ProjectOptions {
    /// Describe a new project using the public `gpui-mcp` repository.
    #[must_use]
    pub fn new(name: impl Into<String>, destination: impl Into<PathBuf>) -> Self {
        Self {
            name: name.into(),
            destination: destination.into(),
            dependencies: ProjectDependencies::PublicRepository,
            window_decorations: OutputWindowDecorations::Native,
        }
    }

    /// Use an explicit source checkout instead of the public repository.
    ///
    /// This is useful for offline development and for testing unpublished
    /// changes. The generated manifest records the canonical checkout path.
    #[must_use]
    pub fn with_local_workspace(mut self, workspace: impl Into<PathBuf>) -> Self {
        self.dependencies = ProjectDependencies::LocalWorkspace(workspace.into());
        self
    }

    /// Select the generated OS-window decoration policy.
    #[must_use]
    pub fn with_window_decorations(mut self, decorations: OutputWindowDecorations) -> Self {
        self.window_decorations = decorations;
        self
    }

    /// Cargo package/application identifier.
    #[must_use]
    pub fn name(&self) -> &str {
        &self.name
    }

    /// Destination that must not already exist.
    #[must_use]
    pub fn destination(&self) -> &Path {
        &self.destination
    }
}

/// Create a complete Cargo/GPUI project atomically in a new destination.
///
/// # Errors
///
/// The destination must not exist and the package name must be safe for Cargo
/// and MCP discovery. An explicitly selected local workspace must contain the
/// integration crates and the vendored GPUI patch.
pub fn scaffold_project(options: &ProjectOptions) -> Result<PathBuf, ScaffoldError> {
    validate_package_name(&options.name)?;
    if options.destination.exists() {
        return Err(ScaffoldError::DestinationExists {
            path: options.destination.clone(),
        });
    }
    let dependencies = match &options.dependencies {
        ProjectDependencies::PublicRepository => ManifestDependencies::PublicRepository,
        ProjectDependencies::LocalWorkspace(path) => {
            let workspace = path
                .canonicalize()
                .map_err(|source| ScaffoldError::Workspace {
                    path: path.clone(),
                    source,
                })?;
            validate_workspace(&workspace)?;
            ManifestDependencies::LocalWorkspace(cargo_path(&workspace)?)
        }
    };
    let destination = absolute_destination(&options.destination)?;
    let parent = destination
        .parent()
        .ok_or_else(|| ScaffoldError::InvalidDestination {
            path: destination.clone(),
        })?;
    fs::create_dir_all(parent).map_err(|source| ScaffoldError::Io {
        operation: "create destination parent",
        path: parent.to_owned(),
        source,
    })?;
    let parent = parent.canonicalize().map_err(|source| ScaffoldError::Io {
        operation: "canonicalize destination parent",
        path: parent.to_owned(),
        source,
    })?;
    let file_name = destination
        .file_name()
        .and_then(|name| name.to_str())
        .ok_or_else(|| ScaffoldError::InvalidDestination {
            path: destination.clone(),
        })?;
    let nonce = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map_or(0, |duration| duration.as_nanos());
    let staging = parent.join(format!(
        ".{file_name}.gpui-mcp-scaffold-{}-{nonce}",
        std::process::id()
    ));
    let mut guard = StagingGuard::new(staging.clone());
    fs::create_dir(&staging).map_err(|source| ScaffoldError::Io {
        operation: "create staging directory",
        path: staging.clone(),
        source,
    })?;
    create_project_files(
        &staging,
        &options.name,
        &dependencies,
        options.window_decorations,
    )?;
    fs::rename(&staging, &destination).map_err(|source| ScaffoldError::Io {
        operation: "publish scaffolded project",
        path: destination.clone(),
        source,
    })?;
    guard.disarm();
    Ok(destination)
}

fn create_project_files(
    root: &Path,
    name: &str,
    dependencies: &ManifestDependencies,
    window_decorations: OutputWindowDecorations,
) -> Result<(), ScaffoldError> {
    let src = root.join("src");
    let ui = root.join("ui");
    for directory in [&src, &ui] {
        fs::create_dir(directory).map_err(|source| ScaffoldError::Io {
            operation: "create project directory",
            path: directory.clone(),
            source,
        })?;
    }
    let title = name
        .split(['-', '_'])
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut characters = part.chars();
            characters.next().map_or_else(String::new, |first| {
                first.to_ascii_uppercase().to_string() + characters.as_str()
            })
        })
        .collect::<Vec<_>>()
        .join(" ");
    let bindings = BindingDocument::new().with_binding(Binding::Event {
        target: BindingTarget::Id(ElementId::new("save")),
        event: UiEvent::Click,
        handler: HandlerId::new("save_document"),
    });
    let bindings = bindings.to_ron_pretty().map_err(ScaffoldError::Bindings)?;
    let files = [
        (root.join("Cargo.toml"), cargo_manifest(name, dependencies)),
        (src.join("main.rs"), main_rs(name, &title)),
        (
            src.join("window.rs"),
            window_decorations.rust_module_source(),
        ),
        (ui.join("app.html"), app_html(&title)),
        (ui.join("app.css"), APP_CSS.to_owned()),
        (ui.join("app.bindings.ron"), bindings),
    ];
    for (path, contents) in files {
        fs::write(&path, contents).map_err(|source| ScaffoldError::Io {
            operation: "write project file",
            path,
            source,
        })?;
    }
    Ok(())
}

enum ManifestDependencies {
    PublicRepository,
    LocalWorkspace(String),
}

fn cargo_manifest(name: &str, dependencies: &ManifestDependencies) -> String {
    let dependencies = match dependencies {
        ManifestDependencies::PublicRepository => format!(
            r#"gpui = "0.2.2"
gpui-mcp = {{ git = "{GPUI_MCP_REPOSITORY}", branch = "main" }}
gpui-mcp-html = {{ git = "{GPUI_MCP_REPOSITORY}", branch = "main", features = ["dev-watch"] }}

[patch.crates-io]
gpui = {{ git = "{GPUI_MCP_REPOSITORY}", branch = "main" }}"#
        ),
        ManifestDependencies::LocalWorkspace(root) => format!(
            r#"gpui = "0.2.2"
gpui-mcp = {{ path = "{root}/crates/gpui-mcp" }}
gpui-mcp-html = {{ path = "{root}/crates/gpui-mcp-html", features = ["dev-watch"] }}

[patch.crates-io]
gpui = {{ path = "{root}/vendor/gpui" }}"#
        ),
    };
    format!(
        r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2024"

[dependencies]
{dependencies}

[workspace]
"#
    )
}

#[allow(clippy::too_many_lines)] // The generated starter is clearer as one auditable template.
fn main_rs(app_id: &str, title: &str) -> String {
    format!(
        r#"use std::path::PathBuf;
use std::time::Duration;

use gpui::{{
    App, AppContext, Application, Bounds, Context, IntoElement, Render, Timer, Window, px, size,
}};
use gpui_mcp::{{ActionOutcome, BridgeConfig, BridgeHandle}};
use gpui_mcp_html::{{
    HandlerId, HookRegistry, LiveHtmlSession, ProjectPaths, ProjectSnapshot, ProjectWatcher,
}};

const APP_ID: &str = "{app_id}";
const TITLE: &str = "{title}";

mod window;

struct AppView {{
    session: LiveHtmlSession,
    watcher: ProjectWatcher,
    _bridge: BridgeHandle,
}}

impl AppView {{
    fn poll_project(&mut self) {{
        let change = match self.watcher.poll() {{
            Ok(change) => change,
            Err(error) => {{
                eprintln!("project watcher error: {{error}}");
                return;
            }}
        }};
        let Some(change) = change else {{ return; }};
        let source = match ProjectSnapshot::load(self.watcher.paths()) {{
            Ok(snapshot) => snapshot.into_live_document_source(),
            Err(error) => {{
                eprintln!("could not read changed project: {{error}}");
                return;
            }}
        }};
        match self.session.preview_source(self.session.revision(), source) {{
            Ok(preview) if preview.applied => eprintln!(
                "hot reloaded revision {{}} from {{:?}}",
                preview.document.revision,
                change.files()
            ),
            Ok(preview) => eprintln!("hot reload rejected: {{:?}}", preview.diagnostics),
            Err(error) => eprintln!("hot reload conflict: {{}}", error.message),
        }}
    }}
}}

impl Render for AppView {{
    fn render(&mut self, window: &mut Window, cx: &mut Context<Self>) -> impl IntoElement {{
        self.session.render(window, cx)
    }}
}}

fn build_live(window: &Window, cx: &App) -> Result<AppView, String> {{
    let bridge = BridgeHandle::install(
        window,
        cx,
        BridgeConfig::new(APP_ID, TITLE).enable_live_document(),
    )
    .map_err(|error| error.to_string())?;
    let paths = ProjectPaths::open(PathBuf::from(env!("CARGO_MANIFEST_DIR")))
        .map_err(|error| error.to_string())?;
    let source = ProjectSnapshot::load(&paths)
        .map_err(|error| error.to_string())?
        .into_live_document_source();
    let mut hooks = HookRegistry::new();
    hooks
        .register_event(HandlerId::new("save_document"), |event, _, _| {{
            eprintln!("{{}} clicked", event.element_id().as_str());
            ActionOutcome::Handled
        }})
        .map_err(|error| error.to_string())?;
    let session = LiveHtmlSession::compile(source, bridge.automation(), hooks)
        .map_err(|error| error.to_string())?;
    session
        .register_mcp_preview(&bridge)
        .map_err(|error| error.to_string())?;
    let watcher = ProjectWatcher::new(paths).map_err(|error| error.to_string())?;
    Ok(AppView {{ session, watcher, _bridge: bridge }})
}}

fn main() {{
    Application::new().run(|cx: &mut App| {{
        gpui_mcp_html::init(cx);
        let bounds = Bounds::centered(None, size(px(800.0), px(600.0)), cx);
        let opened = cx.open_window(
            window::output_window_options(bounds),
            |window, cx| {{
                window.set_window_title(TITLE);
                let app = build_live(window, cx).unwrap_or_else(|error| {{
                    eprintln!("could not initialize application: {{error}}");
                    std::process::exit(1);
                }});
                eprintln!("GPUI MCP endpoint: {{}}", app._bridge.endpoint_path().display());
                let view = cx.new(|_| app);
                let weak_view = view.downgrade();
                window
                    .spawn(cx, async move |cx| {{
                        loop {{
                            Timer::after(Duration::from_millis(50)).await;
                            if weak_view
                                .update(cx, |view, cx| {{
                                    view.poll_project();
                                    cx.notify();
                                }})
                                .is_err()
                            {{
                                break;
                            }}
                        }}
                    }})
                    .detach();
                cx.new(|cx| gpui_mcp_html::NativeRoot::new(view, window, cx))
            }},
        );
        if let Err(error) = opened {{
            eprintln!("could not open application window: {{error}}");
            cx.quit();
            return;
        }}
        cx.activate(true);
    }});
}}
"#
    )
}

fn app_html(title: &str) -> String {
    format!(
        r#"<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{title}</title>
</head>
<body id="app">
  <header>
    <h1>{title}</h1>
  </header>
  <main>
    <p>Edit <code>ui/app.html</code> and <code>ui/app.css</code>.</p>
    <button id="save" type="button">Save</button>
  </main>
</body>
</html>
"#
    )
}

const APP_CSS: &str = r"body {
  display: flex;
  flex-direction: column;
  gap: 16px;
  padding: 24px;
  background-color: #10141c;
  color: #e8eef7;
}

main {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

button {
  padding: 8px;
  background-color: #1677ff;
  color: #ffffff;
  border-radius: 6px;
}
";

fn validate_package_name(name: &str) -> Result<(), ScaffoldError> {
    let mut characters = name.chars();
    let valid = characters
        .next()
        .is_some_and(|character| character.is_ascii_lowercase())
        && characters.all(|character| {
            character.is_ascii_lowercase() || character.is_ascii_digit() || character == '-'
        });
    if valid && name.len() <= 64 {
        Ok(())
    } else {
        Err(ScaffoldError::InvalidPackageName {
            name: name.to_owned(),
        })
    }
}

fn validate_workspace(workspace: &Path) -> Result<(), ScaffoldError> {
    for manifest in [
        workspace.join("crates/gpui-mcp/Cargo.toml"),
        workspace.join("crates/gpui-mcp-html/Cargo.toml"),
        workspace.join("vendor/gpui/Cargo.toml"),
    ] {
        if !manifest.is_file() {
            return Err(ScaffoldError::MissingWorkspaceCrate { manifest });
        }
    }
    Ok(())
}

fn cargo_path(path: &Path) -> Result<String, ScaffoldError> {
    let raw = path.to_string_lossy();
    let path = if let Some(path) = raw.strip_prefix(r"\\?\UNC\") {
        format!("//{}", path.replace('\\', "/"))
    } else {
        raw.strip_prefix(r"\\?\").unwrap_or(&raw).replace('\\', "/")
    };
    if path.contains(['"', '\n', '\r']) {
        Err(ScaffoldError::InvalidDependencyPath { path })
    } else {
        Ok(path)
    }
}

fn absolute_destination(destination: &Path) -> Result<PathBuf, ScaffoldError> {
    if destination.is_absolute() {
        Ok(destination.to_owned())
    } else {
        std::env::current_dir()
            .map(|current| current.join(destination))
            .map_err(|source| ScaffoldError::Io {
                operation: "resolve current directory",
                path: destination.to_owned(),
                source,
            })
    }
}

struct StagingGuard {
    path: PathBuf,
    armed: bool,
}

impl StagingGuard {
    fn new(path: PathBuf) -> Self {
        Self { path, armed: true }
    }

    fn disarm(&mut self) {
        self.armed = false;
    }
}

impl Drop for StagingGuard {
    fn drop(&mut self) {
        if self.armed {
            let _ = fs::remove_dir_all(&self.path);
        }
    }
}

/// Project scaffolding failure.
#[derive(Debug, thiserror::Error)]
pub enum ScaffoldError {
    /// Package name is outside the supported Cargo/MCP identifier subset.
    #[error("invalid Cargo package name `{name}`")]
    InvalidPackageName {
        /// Rejected package name.
        name: String,
    },
    /// Scaffolding never overwrites an existing path.
    #[error("destination already exists: {path}", path = .path.display())]
    DestinationExists {
        /// Existing destination.
        path: PathBuf,
    },
    /// Destination has no usable UTF-8 final component or parent.
    #[error("invalid destination: {path}", path = .path.display())]
    InvalidDestination {
        /// Rejected destination.
        path: PathBuf,
    },
    /// The local gpui-mcp workspace could not be opened.
    #[error("cannot use gpui-mcp workspace {path}", path = .path.display())]
    Workspace {
        /// Supplied workspace.
        path: PathBuf,
        /// Filesystem failure.
        #[source]
        source: io::Error,
    },
    /// One required local crate manifest is absent.
    #[error("gpui-mcp workspace is missing {manifest}", manifest = .manifest.display())]
    MissingWorkspaceCrate {
        /// Missing manifest.
        manifest: PathBuf,
    },
    /// Local dependency path cannot safely be quoted in TOML.
    #[error("dependency path cannot be represented safely in Cargo.toml: {path}")]
    InvalidDependencyPath {
        /// Rejected string path.
        path: String,
    },
    /// Filesystem operation failed.
    #[error("{operation} at {path}", path = .path.display())]
    Io {
        /// Operation description.
        operation: &'static str,
        /// Affected path.
        path: PathBuf,
        /// Filesystem failure.
        #[source]
        source: io::Error,
    },
    /// Initial RON binding serialization failed.
    #[error("serialize scaffold binding document")]
    Bindings(#[source] BindingDocumentError),
}

#[cfg(test)]
mod tests {
    use super::{OutputWindowDecorations, ProjectOptions, scaffold_project};

    #[test]
    fn scaffold_writes_pure_html_ron_and_rust_project() -> Result<(), Box<dyn std::error::Error>> {
        let temporary = tempfile::tempdir()?;
        let destination = temporary.path().join("sample-app");
        let output = scaffold_project(&ProjectOptions::new("sample-app", &destination))?;

        assert_eq!(output, destination);
        assert!(destination.join("Cargo.toml").is_file());
        assert!(destination.join("src/main.rs").is_file());
        assert!(destination.join("src/window.rs").is_file());
        assert!(destination.join("ui/app.html").is_file());
        assert!(destination.join("ui/app.bindings.ron").is_file());
        let manifest = std::fs::read_to_string(destination.join("Cargo.toml"))?;
        assert!(manifest.contains("[workspace]"));
        assert!(manifest.contains("features = [\"dev-watch\"]"));
        assert!(manifest.contains("https://github.com/themixednuts/gpui-mcp"));
        assert!(manifest.contains("[patch.crates-io]"));
        assert!(!manifest.contains("path ="));
        let main = std::fs::read_to_string(destination.join("src/main.rs"))?;
        assert!(main.contains("ProjectWatcher"));
        assert!(main.contains("enable_live_document"));
        assert!(main.contains("NativeRoot::new"));
        assert!(main.contains("window::output_window_options(bounds)"));
        let window = std::fs::read_to_string(destination.join("src/window.rs"))?;
        assert!(window.contains("appears_transparent: false"));
        assert!(window.contains("WindowDecorations::Server"));
        let html = std::fs::read_to_string(destination.join("ui/app.html"))?;
        assert!(!html.contains("data-htmlswap-"));
        Ok(())
    }

    #[test]
    fn custom_decorations_generate_runnable_cross_platform_window_options()
    -> Result<(), Box<dyn std::error::Error>> {
        let temporary = tempfile::tempdir()?;
        let destination = temporary.path().join("custom-window");
        scaffold_project(
            &ProjectOptions::new("custom-window", &destination)
                .with_window_decorations(OutputWindowDecorations::Custom),
        )?;

        let window = std::fs::read_to_string(destination.join("src/window.rs"))?;
        assert!(window.contains("appears_transparent: true"));
        assert!(window.contains("WindowDecorations::Client"));
        Ok(())
    }

    #[test]
    fn local_workspace_is_an_explicit_offline_override() -> Result<(), Box<dyn std::error::Error>> {
        let temporary = tempfile::tempdir()?;
        let destination = temporary.path().join("offline-app");
        let workspace = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
        scaffold_project(
            &ProjectOptions::new("offline-app", &destination).with_local_workspace(workspace),
        )?;

        let manifest = std::fs::read_to_string(destination.join("Cargo.toml"))?;
        assert!(manifest.contains("path ="));
        assert!(manifest.contains("vendor/gpui"));
        assert!(!manifest.contains("git ="));
        Ok(())
    }
}
